CREATE UNIQUE INDEX "addresses_one_default_per_user" ON "public"."addresses" USING "btree" ("user_id") WHERE "is_default";
CREATE INDEX "addresses_user_id_idx" ON "public"."addresses" USING "btree" ("user_id");
CREATE INDEX "idx_notifications_created_at" ON "public"."notifications" USING "btree" ("created_at" DESC);
CREATE INDEX "idx_notifications_unread" ON "public"."notifications" USING "btree" ("user_id", "is_read");
CREATE INDEX "idx_notifications_user" ON "public"."notifications" USING "btree" ("user_id");
CREATE INDEX "idx_orders_customer" ON "public"."orders" USING "btree" ("customer_id");
CREATE INDEX "idx_orders_merchant" ON "public"."orders" USING "btree" ("merchant_id");
CREATE INDEX "idx_payments_customer" ON "public"."payments" USING "btree" ("customer_id");
CREATE INDEX "idx_payments_order" ON "public"."payments" USING "btree" ("order_id");
CREATE INDEX "idx_profiles_email" ON "public"."profiles" USING "btree" ("email");
CREATE INDEX "orders_customer_id_idx" ON "public"."orders" USING "btree" ("customer_id");
CREATE INDEX "orders_merchant_id_idx" ON "public"."orders" USING "btree" ("merchant_id");
CREATE INDEX "payments_customer_id_idx" ON "public"."payments" USING "btree" ("customer_id");
CREATE INDEX "payments_order_id_idx" ON "public"."payments" USING "btree" ("order_id");
CREATE INDEX "payments_provider_idx" ON "public"."payments" USING "btree" ("provider");
CREATE INDEX "profiles_email_idx" ON "public"."profiles" USING "btree" ("email");
CREATE UNIQUE INDEX "vouchers_code_key" ON "public"."vouchers" USING "btree" ("code");
CREATE INDEX "wallet_transactions_user_created_idx" ON "public"."wallet_transactions" USING "btree" ("user_id", "created_at" DESC);
CREATE INDEX idx_messages_sender_id ON public.messages(sender_id);
CREATE INDEX idx_messages_receiver_id ON public.messages(receiver_id);
CREATE INDEX idx_messages_store_id ON public.messages(store_id);
